.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CSPICE\-MKSPK" "1" "April 2017" "" "General Commands Manual"
.
.SH "NAME"
\fBcspice\-mkspk\fR \- creates an SPK file from trajectory information
.
.SH "SYNOPSIS"
\fBcspice mkspk\fR \fB\-setup\fR \fIsetup_file\fR [\fIoptions\fR]
.
.br
\fBcspice mkspk\fR \fB\-template\fR [\fIinput_type\fR \fIoutput_type\fR]
.
.br
\fBcspice mkspk\fR \fB\-u\fR | \fB\-h\fR
.
.SH "DESCRIPTION"
\fBMKSPK\fR is an utility program that generates a new, or appends data to an existing, spacecraft or target body\'s ephemeris file in SPICE SPK format using one of the following SPK types: 5, 8, 9, 10, 12, 13, 15, 17\. This SPK file is a binary file constructed according to the SPICE DAF (Double Precision Array File) architecture, containing one or more SPK data segments\.
.
.P
The \fBMKSPK\fR program accepts one ASCII text file containing descriptions of input data (setup file) and a second ASCII text file (input file) containing the source ephemeris data to be processed\.
.
.P
Source ephemeris data can be time ordered lists of states (positions and velocities), sets of conic elements, sets of two\-line elements, or a single set of equinoctial elements\. All input data must be defined in a reference frame and relative to a body center both of which are specified in the setup file\.
.
.P
The program allows the user to optionally specify some descriptive text in a separate file (comment file) to be placed into the "comment area" of the SPK ephemeris file\. (Doing this is highly recommended\.)
.
.P
For archival documentation purposes the content of the MKSPK setup file is automatically placed at the end of the "comment area" of the SPK file\.
.
.P
\fBMKSPK\fR is part of the CSPICE Toolkit\. See \fBcspice\fR(7) for more information\.
.
.SH "OPTIONS"
Command lines options can be provided in any order\. Option keys must be strictly lowercase\.
.
.TP
\fB\-setup\fR \fIsetup_file\fR
Provide the setup file name\. If a setup file name isn\'t provided on the command line using the \fB\-setup\fR key, the program will prompt for it\. If options \fB\-input\fR or \fB\-output\fR are provided, any file names assigned using setup file keywords are ignored\.
.
.TP
\fB\-input\fR \fIinput_file\fR
Provide the input data file name\. The input file must already exist\.
.
.TP
\fB\-output\fR \fIoutput_file\fR
Provide the output SPK file name\. The output must not exist unless the \fB\-append\fR option or the corresponding setup file keyword tells the program to run in the append mode\.
.
.TP
\fB\-append\fR
Append new data to the specified output SPK file\. If the SPK file specified after the \fB\-output\fR option doesn\'t exist, then a new SPK file with the name specified will be created\.
.
.IP
CAUTION: if the program fails for any reason, it, in most cases, deletes the output file, even if it was appending data to an existing SPK file\.
.
.TP
\fB\-u\fR, \fB\-usage\fR
Display usage information\.
.
.TP
\fB\-h\fR, \fB\-help\fR
Display a brief summary of the program\'s functionality\.
.
.TP
\fB\-t\fR, \fB\-template\fR [\fIinput_type\fR \fIoutput_type\fR]
Display either the complete setup file template or a type\-specific setup file template and exit\. If specified by itself, the program displays the complete setup file template including all required, optional, and conditional setup file keywords\. To display a more concise, type\-specific template, the \fIinput_type\fR (\fBstates\fR, \fBelements\fR, \fBeq_elements\fR, or \fBtl_elements\fR) and the \fIoutput_type\fR (\fB5\fR, \fB8\fR, \fB9\fR, \fB10\fR, \fB12\fR, \fB13\fR, \fB15\fR or \fB17\fR) can be specified\. Such templates will include only keywords applicable for the specified type combination\.
.
.SH "SEE ALSO"
\fBcspice\fR(7)
.
.P
Full documentation is provided by package cspice\-doc on /usr/share/doc/cspice or it can be obtained online on https://naif\.jpl\.nasa\.gov/pub/naif/toolkit_docs/C/\.
