.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Rock Storm <rockstorm@gmx.com>,
.\"
.TH CSPICE-INSPEKT 1
.SH NAME
cspice-inspekt \- interactively examine the contents of an E-Kernel

.SH SYNOPSIS
.B cspice-inspekt

.SH DESCRIPTION
.B cspice-inspekt
is an interactive command-line program that examines the contents of an events component (ESQ) of an E-kernel. To access the built-in help please type "help;" (or "HELP;"), a menu will be displayed and at the prompt "Option: " type the number or letter shown in parentheses to the left of the topic of interest and hit RETURN. You will be presented with a screen of text that describes the topic.
.PP
.B cspice-inspekt
is part of the SPICE Toolkit. See \fBcspice\fR(7).

.SH SEE ALSO
.BR cspice (7).

.SH AUTHOR
This manual page was written by Rock Storm <rockstorm@gmx.com> based on the official SPICE documentation. See http://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/index.html for more information.
