.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CSPICE\-CHRONOS" "1" "April 2017" "" "General Commands Manual"
.
.SH "NAME"
\fBcspice\-chronos\fR \- convert time from one supported system/type to another
.
.SH "SYNOPSIS"
.
.TP
\fBcspice chronos\fR
\fB\-setup\fR \fIfile\fR
.
.br
\fB\-from\fR \fItime_system\fR
.
.br
\fB\-to\fR \fItime_system\fR
.
.br
\fB\-time\fR \fIinput_time\fR | \fB\-batch\fR
.
.br
[\fIoptions\fR]
.
.SH "DESCRIPTION"
\fBCHRONOS\fR is a utility program that converts time between various time systems\. It supports the following time systems:
.
.TP
UTC
Universal Time Coordinated; UTC is a system of time keeping that gives a name to each instant of time of the International Atomic Time system; refer to the NAIF Toolkit TIME\.REQ document for more discussion regarding UTC;
.
.TP
ET
Ephemeris Time; Ephemeris time is the uniform time scale represented by the independent variable in the differential equations that describe the motions of the planets, sun and moon\. CHRONOS deals with one of the two forms of ET \-\- Barycentric Dynamical Time (TDB) which is used when describing the motion of bodies with respect to the solar system barycenter; refer to the NAIF Toolkit TIME\.REQ document for more discussion regarding ET;
.
.TP
SCLK
Spacecraft On\-Board Clock Time; SCLK is the on\-board time\-keeping mechanism that triggers most spacecraft events and is the fundamental time measurement for referencing most spacecraft activities and instrument data; refer to the NAIF Toolkit SCLK\.REQ document for more discussion regarding SCLK;
.
.TP
LST
Local Solar Time; LST is simply a measure of angles between landing (sub\-spacecraft) and sub\-solar meridians on the surface of a body expressed as a "24 hour" local clock\.
.
.P
\fBCHRONOS\fR is part of the CSPICE Toolkit\. See \fBcspice\fR(7) for more information\.
.
.SH "OPTIONS"
Command line keys \'\-XXXXXXX\' are case insensitive\. Any of the command line options can be present in the command line multiple times (in such cases the last appearance of a key takes precedence\.) The order in which options are specified is insignificant\.
.
.TP
\fB\-setup\fR \fIsetup_file\fR
Specify a setup file name or directly list the names of the SPICE kernels to be used\. If \fIsetup_file\fR is not present or is blank, it tries to obtain it from the environment variable CHRONOS_SETUP_FILE\.
.
.TP
\fB\-from\fR \fItime_system\fR
Specify the time system of the input time\.
.
.TP
\fB\-fromtype\fR \fItime_type\fR
Specify the time type of the input time\. If it\'s not present or is blank, it is assumed the default time type for the input time system (SCET for UTC and ET, SCLK for SCLK, and LST for LST)\.
.
.TP
\fB\-to\fR \fItime_system\fR
Specify the time system of the output time\.
.
.TP
\fB\-totype\fR \fItime_type\fR
Specify the time type of the output time\. If it\'s not present or is blank, it is assumed the default time type for the output time system (SCET for UTC and ET, SCLK for SCLK and LST for LST)\.
.
.TP
\fB\-format\fR \fIoutput_format\fR
Specify a custom format for the output time\. If a format specification is not present or is blank, it looks for a specification in the setup file and, if such is also not available, it uses the default format\.
.
.TP
\fB\-time\fR \fItime\fR
Specify the input time\. Most time types of UTC and ET systems require input time to be in a form of a time string recognized by TIME subsystem of SPICE\.
.
.TP
\fB\-batch\fR
Tell the program to take input time(s) from standard input instead of the command line\. If it\'s present, the program ignores any input time provided after the \fB\-time\fR option\.
.
.TP
\fB\-sc\fR \fIsc_id\fR
Specify the NAIF ID for the spacecraft\. If \fIsc_id\fR is not present, the program looks for it in the setup file\.
.
.TP
\fB\-center\fR \fIbody_id\fR
Specify the NAIF ID for the center body\. If \fIbody_id\fR is not present, the program looks for it in the setup file\.
.
.TP
\fB\-landingtime\fR \fItime\fR
Specify the UTC time of the landing\. If \fItime\fR is not present, the program looks for it in the setup file\.
.
.TP
\fB\-sol1index\fR \fIindex\fR
Specify the SOL index for the first day on surface\. If \fIindex\fR is not present, the program looks for it in the setup file\.
.
.TP
\fB\-nolabel\fR
Tell the program to not display [SYSTEM]/[TYPE] following the output time string\.
.
.TP
\fB\-trace\fR
Tell the program to display trace information including, complete command line, names of the loaded SPICE kernel files, all relevant setup information, etc\. This option overrules the \fB\-nolabel\fR option\.
.
.TP
\fB\-template\fR
Display setup file template\.
.
.TP
\fB\-h\fR, \fB\-help\fR
Display help information\.
.
.TP
\fB\-u\fR, \fB\-usage\fR
Display usage information\.
.
.SH "SEE ALSO"
\fBcspice\fR(7)
.
.P
Full documentation is provided by package cspice\-doc on /usr/share/doc/cspice or it can be obtained online on https://naif\.jpl\.nasa\.gov/pub/naif/toolkit_docs/C/\.
