.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CSPICE\-INSPEKT" "1" "April 2017" "" "General Commands Manual"
.
.SH "NAME"
\fBcspice\-inspekt\fR \- interactively examine the contents of an E\-Kernel
.
.SH "SYNOPSIS"
\fBcspice inspekt\fR
.
.SH "DESCRIPTION"
\fBINSPEKT\fR is an interactive command\-line program that examines the contents of an events component (ESQ) of an E\-kernel\. To access the built\-in help type "help;" (or "HELP;"), a menu will be displayed\. At the prompt "Option: " type the number or letter shown in parentheses to the left of the topic of interest and hit RETURN\. You will be presented with a screen of text that describes the topic\.
.
.P
\fBINSPEKT\fR is part of the CSPICE Toolkit\. See \fBcspice\fR(7) for more information\.
.
.SH "SEE ALSO"
\fBcspice\fR(7)
.
.P
Full documentation is provided by package cspice\-doc on /usr/share/doc/cspice or it can be obtained online on https://naif\.jpl\.nasa\.gov/pub/naif/toolkit_docs/C/\.
