.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Rock Storm <rockstorm@gmx.com>,
.\"
.TH CSPICE-SPACIT 1
.SH NAME
cspice-spacit \- manipulate and examine SPICE binary kernels

.SH SYNOPSIS
.B cspice-spacit

.SH DESCRIPTION
.B cspice-spacit
is an interactive menu driven program which provides a collection of services useful for manipulating and examining SPICE binary kernel files. The program may be used to convert SPICE binary kernel files into equivalent ASCII files, called SPICE transfer files, and to convert the SPICE transfer files back to binary. SPACIT may also be used to summarize the information contained in SPICE binary kernel files and to read the comments contained in the comment area of a SPICE binary kernel file.
.PP
The program currently supports the CK, EK, PCK, and SPK SPICE binary kernel file formats.
.PP
.B cspice-spacit
is part of the SPICE Toolkit. See \fBcspice\fR(7).

.SH SEE ALSO
.BR cspice (7).

.SH AUTHOR
This manual page was written by Rock Storm <rockstorm@gmx.com> based on the official SPICE documentation. See http://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/index.html for more information.
