.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CSPICE\-CKBRIEF" "1" "April 2017" "" "General Commands Manual"
.
.SH "NAME"
\fBcspice\-ckbrief\fR \- displays a summary for binary CK files
.
.SH "SYNOPSIS"
\fBcspice ckbrief\fR [\fIoptions\fR] \fIfile\fR [\fIfile\fR \.\.\.]
.
.SH "DESCRIPTION"
\fBCKBRIEF\fR is a command line program that displays a summary of the contents and time coverage for one or more binary CK files\. The program displays a summary for each CK file listed on the command line, in a list file, and/or a meta\-kernel\. It can display coverage boundaries as ephemeris time (ET) in calendar format, as UTC time in "year\-month\-day" or "day\-of\-year" format, or as on\-board clock (SCLK) time in string or encoded format\. It can display the summary in a variety of formats, with or without showing the names of the frames associated with spacecraft or structure IDs or the names/IDs of the frames with respect to which orientation is provided\.
.
.P
In order for the program to display times in the default format or any other format (except encoded SCLK), both an LSK file and an SCLK file containing required time correlation data must be provided on the command line, in a list file (specified with the option \fB\-f\fR described later in this document), or in a meta\-kernel file given on the command line or in the list file\.
.
.P
\fBCKBRIEF\fR is part of the CSPICE Toolkit\. See \fBcspice\fR(7) for more information\.
.
.SH "OPTIONS"
.
.SS "Options Controlling Output Summary Format"
.
.TP
\fB\-dump\fR
Display a summary of interpolation interval boundaries, the actual time periods for which the file provides data, for each of the segments in the file\.
.
.TP
\fB\-nm\fR
Display a summary of segment boundaries for each of the structures in the file\. This option is ignored when \fB\-dump\fR is specified\.
.
.TP
\fB\-rel\fR
Display, in the additional right\-hand column, frames with respect to which the orientation is given in the CK segments\. For frames known to SPICE, built\-in or defined in the FK files provided to the program along with CK, LSK, and SCLK files, the program displays names; for unrecognized frames, the program displays IDs\. This option is ignored when \fB\-g\fR is specified\.
.
.TP
\fB\-n\fR
Display frame names associated with the structure IDs instead of the numeric structure IDs\. For frames known to SPICE, defined in the FK files provided to the program, the program displays names; for unrecognized frames, the program displays IDs with the prefix "NO FRAME FOR \fIid\fR"\.
.
.TP
\fB\-t\fR
Use the tabular display format in which coverage information for all structures from each file is presented in a single table with the structure IDs provided in the left column rather than in the table headers\.
.
.TP
\fB\-g\fR
Use the grouping display format, in which information for structures with the same coverage is grouped together into blocks with the coverage begin and end time shown first, and the list of structure IDs shown below them\. This option is ignored when \fB\-dump\fR or \fB\-t\fR are specified\.
.
.SS "Options Controlling Output Time Format"
In order for the program to display times in the default format or any other format (except encoded SCLK), both an LSK file and an SCLK file containing required time correlation data must be provided\.
.
.P
When multiple options controlling the output time format are given at the same time, the option specified last on the command line takes precedence\.
.
.TP
\fB\-utc\fR
Display time tags as UTC in the "YYYY\-MON\-DD HR:MN:SC\.DDD" format (needs LSK and SCLK)\.
.
.TP
\fB\-utcdoy\fR
Display time tags as UTC times in the "YYYY\-DOY // HR:MN:SC\.DDD" format (needs LSK and SCLK)\.
.
.TP
\fB\-sclk\fR
Display time tags as SCLK strings (needs LSK and SCLK)\.
.
.TP
\fB\-dpsclk\fR
Display time tags as encoded SCLKs (ticks)\.
.
.SS "Miscellaneous Options"
.
.TP
\fB\-a\fR
Display a summary for multiple CKs listed on the command line and/or provided in meta\-kernels and/or a list file as if all data from these CKs were provided in a single CK file\.
.
.TP
\fIid\fR
One or more (up to 100) structure IDs may be listed on the command line to tell BRIEF to display summary information only for the specified structure(s)\.
.
.TP
\fB\-f\fR \fIlist_file\fR
Display a summary for the files whose names are listed in the text file \fIlist_file\fR\. The file names can be provided one\-per\-line or a few\-per\-line separated by one or more spaces\.
.
.TP
\fB\-h\fR
Display a complete usage message listing all options and exit\.
.
.TP
\fB\-v\fR
Display just the version line and exit\.
.
.SH "SEE ALSO"
\fBcspice\fR(7)
.
.P
Full documentation is provided by package cspice\-doc on /usr/share/doc/cspice or it can be obtained online on https://naif\.jpl\.nasa\.gov/pub/naif/toolkit_docs/C/\.
