.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CSPICE\-VERSION" "1" "April 2017" "" "General Commands Manual"
.
.SH "NAME"
\fBcspice\-version\fR \- prints version and details of the CSPICE Toolkit
.
.SH "SYNOPSIS"
\fBcspice version\fR [\fIoptions\fR]
.
.SH "DESCRIPTION"
\fBVERSION\fR is a command\-line program that prints the current version number of the SPICE Toolkit\.
.
.P
\fBVERSION\fR is part of the CSPICE Toolkit\. See \fBcspice\fR(7) for more information\.
.
.SH "OPTIONS"
To display only the SPICE toolkit version, VERSION should be executed without command arguments\.
.
.TP
\fB\-a\fR, \fB\-all\fR
Display all parameters for the environment for which the toolkit package was prepared, including SPICE toolkit version, system ID, operating system, compiler, and binary file format, max and min values for double precision and integer numbers\.
.
.TP
\fB\-v\fR, \fB\-version\fR
Display the version of the VERSION program\.
.
.TP
\fB\-h\fR, \fB\-help\fR
Display usage information\.
.
.SH "SEE ALSO"
\fBcspice\fR(7)
.
.P
Full documentation is provided by package cspice\-doc on /usr/share/doc/cspice or it can be obtained online on https://naif\.jpl\.nasa\.gov/pub/naif/toolkit_docs/C/\.
